FROM node:23-slim

RUN apt-get update && apt-get install yarn -y && rm -rf /var/lib/apt/lists/*

WORKDIR /echo

COPY package.json ./

RUN yarn install --frozen-lockfile --non-interactive --prefer-offline
RUN yarn cache clean

COPY . .

CMD ["yarn", "dev"]
